### ISSUE TITLE
Accessing camera from Emulator but not in real device

### ISSUE THREAD

**Issue by demson2** [mgks/Os-FileUp#6]
Hello, I have tried this and it seems only to be working fine on the emulator. When running directly on my device with Android 6.0.1 it accesses only the photo gallery and file system but not the camera. Any Idea?
Thanks

**Comment by mgks** [comment]
Hey,

Probably it's because of permissions i guess but the question isn't
sufficient in itself. You need to profile some log atleast, that is
recorded during the request for file upload.

Try to get more details on the bug.

On 14-May-2017 8:00 PM, "demson2" <notifications@github.com> wrote:

Hello, I have tried this and it seems only to be working fine on the
emulator. When running directly on my device with Android 6.0.1 it accesses
only the photo gallery and file system but not the camera. Any Idea?
Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mgks/Os-FileUp/issues/6>, or mute the thread

**Comment by demson2** [comment]
Hey,
I have just tested it in Android 5.1 and it is accessing the camera correctly. But definitely not in Android 6.0.1. Any Idea of which access right should be set?

**Comment by mgks** [comment]
Android set individual permissions required 6.0 afterwards if that's the case and you're having problems getting users permission to use the camera and storage. Try go to settings and check which assets are permitted to your app to use.

Still dude, i need the log to say anything else.

**Comment by demson2** [comment]
I finally got it sorry. By default Android 6 will not enable access to device by default for security reasons, so one has to explicitly enable it.

Steps to do it:
    - On your device, open the main Settings app .
    - Tap Apps or Application Manager (depending on your device, this may look different).
    - choose FileUp.
    Tap Permissions.
    Next to a permission you want to turn on, move the switch to the right until it turns green.

**Comment by mgks** [comment]
Great!
But, I haven't updated this project in a while, which I will soon I guess to be compatible with all devices available. *there's my fault also*

And also, here you have this - [Android Smart WebView](https://github.com/mgks/Android-SmartWebView)
On which I was working lately and yes, it's updated and has all features and methods required till Android 7.x. You can get that part from there, I tried to write the codes as clean as possible so all parts are easy to find and plugable. Try it and tell me, if it works you can close this issue or let it be open until I fix this project.

**Comment by mgks** [comment]
I've updated the project, now it has all the required changes for latest Android API till 25.
